// src/icons.js
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faHeart as faSolidHeart,
  faDownload,
  faInfoCircle,
  faChevronDown,
  faGraduationCap,
  faVideo,
  faUsers,
  faSignOutAlt,
  faSignInAlt,
  faHome,
  faUpload,
  faBars,
  faTimes,
  faSearch,
  faArrowUp,
  faArrowRight,
  faUserPlus,
  faUserCog,
  faKey,
  faUserSlash,
  faFileExport,
  faUserCircle,
  faUser,
  faArrowLeft,
  faEdit,
  faTrash,
} from "@fortawesome/free-solid-svg-icons";
import { faHeart as faRegularHeart } from "@fortawesome/free-regular-svg-icons";
import {
  faFacebookF,
  faTwitter,
  faXTwitter,
  faLinkedinIn,
  faInstagram,
} from "@fortawesome/free-brands-svg-icons";


library.add(
  faSolidHeart,
  faDownload,
  faInfoCircle,
  faChevronDown,
  faGraduationCap,
  faVideo,
  faUsers,
  faSignOutAlt,
  faSignInAlt,
  faHome,
  faUpload,
  faBars,
  faTimes,
  faSearch,
  faArrowUp,    
  faArrowRight,   
  faUserPlus,     
  faUserCog,      
  faKey,         
  faUserSlash,    
  faFileExport,   
  faUserCircle,   
  faRegularHeart,
  faFacebookF,
  faTwitter,
  faXTwitter,
  faLinkedinIn,
  faInstagram,
  faUser,
  faArrowLeft,
  faEdit,
  faTrash,
);
